version: '3'

services:
  db:
     image: mysql
     restart: always
     ports:
       - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD: 12345678
     volumes:
       - mysql-datavolume:/var/lib/mysql
  adminer:
     image: adminer
     restart: always
     ports:
       - 8090:8080
     links:
       - "db"

volumes:
  mysql-datavolume: