version: '2.1'

services:
  apache:
    image: 'bitnami/apache:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'apache_data:/bitnami'

  db:
     image: mysql
     restart: always
     ports:
       - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD: Technobrainsm1
     links:
       - "apache"

  adminer:
     image: adminer
     restart: always
     ports:
       - 8090:8080
     links:
       - "db"

volumes:
  apache_data:
    driver: local
