#!/usr/bin/env bash
# the server is aws linux box
# servicemix is unloaded and unzipped under /opt folder
yum update -y
cd /opt
wget http://apache.mirror.anlx.net/servicemix/servicemix-7/7.0.1/apache-servicemix-7.0.1.zip
unzip apache-servicemix-7.0.1.zip && mv apache-servicemix-7.0.1 servicemix
# update the ip from 0.0.0.0 to 127.0.0.1
sed -i 's/rmiRegistryHost = 0.0.0.0/rmiRegistryHost = 127.0.0.1/g' servicemix/etc/org.apache.karaf.management.cfg
sed -i 's/#org.ops4j.pax.url.mvn.localRepository=/org.ops4j.pax.url.mvn.localRepository=\/root\/.m2\/repository/g' servicemix/etc/org.ops4j.pax.url.mvn.cfg

#set the name server to be able to access trips-db
FILE=/etc/resolv.conf
chattr -i $FILE
cp /dev/null $FILE
cat <<EOM >$FILE
# Generated by NetworkManager
search mra.trips.ire eu-west-1.compute.internal
nameserver 10.10.3.135
EOM

chattr +i $FILE

#create the datasource file
FILEDS=./servicemix/etc/org.ops4j.datasource-tripsds.cfg
cat <<EOM >$FILEDS
osgi.jdbc.driver.class=oracle.jdbc.OracleDriver
osgi.jdbc.driver.name=oracle
databaseName=trips
user=trips
password=trips
dataSourceName=tripsds1
url=jdbc:oracle:thin:@trips-db:1521/mradev2
EOM