#!/usr/bin/env bash
# the server is aws linux box
# servicemix is unloaded and unzipped under /opt folder
yum update -y
cd /opt
wget http://apache.mirror.anlx.net/servicemix/servicemix-7/7.0.1/apache-servicemix-7.0.1.zip
unzip apache-servicemix-7.0.1.zip && mv apache-servicemix-7.0.1 servicemix
# update the ip from 0.0.0.0 to 127.0.0.1
sed -i 's/rmiRegistryHost = 0.0.0.0/rmiRegistryHost = 127.0.0.1/g' servicemix/etc/org.apache.karaf.management.cfg
sed -i 's/#org.ops4j.pax.url.mvn.localRepository=/org.ops4j.pax.url.mvn.localRepository=\/root\/.m2\/repository/g' servicemix/etc/org.ops4j.pax.url.mvn.cfg

#set the name server to be able to access trips-db
FILE=/etc/resolv.conf
chattr -i $FILE
cp /dev/null $FILE
cat <<EOM >$FILE
# Generated by NetworkManager
search mra.trips.ire eu-west-1.compute.internal
nameserver 10.10.3.135
EOM

chattr +i $FILE

#create the datasource file
FILEDS=./servicemix/etc/org.ops4j.datasource-tripsds.cfg
cat <<EOM >$FILEDS
osgi.jdbc.driver.class=oracle.jdbc.OracleDriver
osgi.jdbc.driver.name=oracle
databaseName=trips
user=trips
password=trips
dataSourceName=tripsds1
url=jdbc:oracle:thin:@trips-db:1521/mradev2
EOM

##install java
cd /opt
wget -c --header "Cookie: oraclelicense=accept-securebackup-cookie"  http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz
#javascript: void(0)
#http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz
mkdir /opt/java
tar -xzf jdk-8u161-linux-x64.tar.gz -C /opt/java
cd java
sudo alternatives --install /usr/bin/java java /opt/java/jdk1.8.0_161/bin/java 2
sudo alternatives --config java
sudo alternatives --install /usr/bin/jar jar /opt/java/jdk1.8.0_161/bin/jar 2
sudo alternatives --set jar /opt/java/jdk1.8.0_161/bin/jar
sudo alternatives --set javac /opt/java/jdk1.8.0_161/bin/javac

echo "#java path" >> /etc/profile
echo "export JAVA_HOME=/opt/java/jdk1.8.0_161" >> /etc/profile
echo "export JRE_HOME=/opt/java/jdk1.8.0_161/jre" >> /etc/profile
echo "export PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin" >> /etc/profile

##install maven
cd /opt
wget http://mirrors.ukfast.co.uk/sites/ftp.apache.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
tar xzvf apache-maven-3.3.9-bin.tar.gz
echo "#maven path" >> /etc/profile

echo "export PATH=$PATH:/opt/apache-maven-3.3.9/bin" >> /etc/profile

source /etc/profile

###clean the downloaded files
rm /opt/jdk-8u161-linux-x64.tar.gz
rm /opt/apache-maven-3.3.9-bin.tar.gz
rm /opt/apache-servicemix-7.0.1.zip