#!/usr/bin/env bash

# Script used to read Property File
FILE_NAME=awscli.config

# Key in Property File
key="Name"

# Variable to hold the Property Value
prop_value=""

getProperty()
{
        prop_key=$1
        prop_value=`cat ${FILE_NAME} | grep ${prop_key} | cut -d'=' -f2`
        echo $prop_value
}

echo "Reading Weblogic Properties ..."
DEPLOYMENT_MODE=$(getProperty "deployment_mode")
ARTIFACT_PATH=$(getProperty "artifact_path")
INSTALLATION_PATH=$(getProperty "installation_path")
CONFIGURE_NETWORK=$(getProperty "configure_network")
CLEAR_ARTIFACTS=$(getProperty "clear_artifacts")
AWS_ACCESS_KEY_ID=$(getProperty "aws_access_key_id")

AWS_SECRET_ACCESS_KEY=$(getProperty "aws_secret_access_key")
REGION=$(getProperty "region")

GIT_USER=$(getProperty "gitUser")
GIT_PASSWORD=$(getProperty "gitPassword")
WL_USER=$(getProperty "wluser_name")




echo "Properties are read ..."
#echo "Key = ${key} ; Value = " ${prop_value}
####BEGIN aws install and configuration
#download install and configure AWS && pip
echo "Checking local or cloud  ..."
if [ "$DEPLOYMENT_MODE" = "aws" ]; then
echo "Cloud  ..."
if ! [ -x "$(command -v pip)" ]; then
  echo 'pip is not installed. Now installing...' >&2
  curl -O https://bootstrap.pypa.io/get-pip.py
  python get-pip.py --user
  #sleep 10
  export PATH=~/.local/bin:$PATH

else
  echo 'pip is already installed' >&2
fi

##credential and configure files for aws
#set the name server to be able to access trips-db

if ! [ -x "$(command -v aws)" ]; then
    echo 'aws cli is not installed. Now installing...' >&2
    pip install awscli --upgrade --user
else
    echo 'aws cli is already installed. ' >&2
fi

echo "Setting .aws directory  ..."
if [ ! -d "$HOME/.aws" ]; then
    mkdir $HOME/.aws
fi


FILE=$HOME/.aws/credentials
cp /dev/null $FILE

cat <<EOM >$FILE
# Generated by installScript1.sh
[default]
aws_access_key_id = $AWS_ACCESS_KEY_ID
aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
EOM

FILE=$HOME/.aws/config
cp /dev/null $FILE

cat <<EOM >$FILE
# Generated by installScript1.sh
[default]
region = eu-west-1
EOM

echo "AWS cloud  installation and configuration is done..."
fi
###################end of aws configuration

yum install unzip -y

##TODO change users to oracle
##TODO check if group and user already exists

getent passwd $WL_USER > /dev/null 2&>1

if [ $? -eq 0 ]; then
    echo "yes the user   exists"  $WL_USER
else
    echo "User is created "  $WL_USER
    useradd $WL_USER
fi

#groupadd -g 54321 ec2-user
#mkdir /u01


DIRECTORY=/u01/software
if [ -d "$DIRECTORY" ]; then
  # Control will enter here if $DIRECTORY exists.
  echo "exists"  $DIRECTORY
else
  echo "create directory "  $DIRECTORY
  mkdir -p $DIRECTORY
fi

DOMAIN1=$(getProperty "domain1")
DOMAIN2=$(getProperty "domain2")
NAMESERVER=$(getProperty "nameserver")
chown $WL_USER:$WL_USER /u01
#chgrp ec2-user /u01




cd /u01/software/

#git clone https://username:password@https://github.com/laksun/ameda.git
#cp /u01/software/trips-plus-devops/weblogic/WAS_1/*.* /u01/software
chmod +x *.sh *.py
export PATH=~/.local/bin:$PATH

echo "Download java weblogic from aws S3"
 if ! [ -e "/u01/software/jdk-8u144-linux-x64.tar.gz" ]; then
    aws s3 cp s3://trips-devops-bucket/jdk-8u144-linux-x64.tar.gz /u01/software/
 else
    echo "/u01/software/jdk-8u144-linux-x64.tar.gz  exists"
 fi

 if ! [ -e "/u01/software/jdk-8u144-linux-x64.rpm" ]; then
    aws s3 cp s3://trips-devops-bucket/jdk-8u144-linux-x64.rpm .
 else
    echo "/u01/software/jdk-8u144-linux-x64.rpm exists"
 fi

 if ! [ -e "/u01/software/fmw_12.2.1.2.0_wls_Disk1_1of1.zip" ]; then
     aws s3 cp s3://trips-devops-bucket/fmw_12.2.1.2.0_wls_Disk1_1of1.zip /u01/software/
     unzip ./fmw_12.2.1.2.0_wls_Disk1_1of1.zip
  else
     echo " fmw_12.2.1.2.0_wls_Disk1_1of1.zip exists"
  fi

chown $WL_USER:$WL_USER /u01/software/*.*
# chown ec2-user:ec2-user /u01/software

#TODO
echo "Configuring network  ..." $CONFIGURE_NETWORK
if   [[  "$CONFIGURE_NETWORK" = "YES" ]]; then
echo "configuring network for values " $DOMAIN1 " -- " $DOMAIN2 " -- "  $NAMESERVER
#set the name server to be able to access trips-db
FILE=/etc/resolv.conf
chattr -i $FILE
cp /dev/null $FILE
cat <<EOM >$FILE
# Generated by NetworkManager
search $DOMAIN1 $DOMAIN2
nameserver $NAMESERVER
EOM

chattr +i $FILE
fi


echo "change the owner of the folder /u01"
chown  -R $WL_USER:$WL_USER /u01

echo " set system requirements for swap"
swapon -va
dd if=/dev/zero of=/swapfile bs=1024 count=5242880
mkswap /swapfile
swapon /swapfile
#TODO set /etc/fstab
# add the following line
# /swapfile               swap                    swap    defaults        0 0

echo "set the hostname to was1"
hostnamectl set-hostname was1
echo "......................."
echo "Weblogic install scripts"
rpm -ivh /u01/software/jdk-8u144-linux-x64.rpm